### ISSUE TITLE
enable fullscreen button + responsive

### ISSUE THREAD

**Issue by maximus321** [a5mith/nodebb-plugin-youtube-lite#10]
Thanks for the plugin.

Most of the user wanted to have the fullscreen button enabled and it was not.

This require this code inside the iframe "allowfullscreen"
Example:
`<iframe class="lazytube" src="//www.youtube.com/embed/8-m75NK5r9U" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>`

Another thing, why not use bootstrap responsive embed so that the video is responsive? (for mobile, etc.)
http://getbootstrap.com/components/#responsive-embed

**Comment by a5mith** [comment]
0.4.7 is now full screen. 

Reason I'm not using Bootstrap is because it defaults to the full width of the container. Which isn't what I wanted from the plugin, hence they're the fixed width. I may amend this for the next major update though.
