### ISSUE TITLE
Plugin doesn't seem to be functioning on fresh NodeBB install

### ISSUE THREAD

**Issue by Chilled9** [a5mith/nodebb-plugin-youtube-lite#12]
Made a fresh NodeBB install today, installed this plugin right away.

Admin panel shows plugin as activated, but any post with a youtube link just shows the text rather than embedding it. We've tried just about any alternative syntax we could think of as well, to no avail. Restarting NodeBB did not help.

No other major changes have been made to the new NodeBB install. Any help would be appreciated.

Thanks.

**Comment by a5mith** [comment]
Use version 0.3.2, I'm reverting back to it at the minute. 

Go into your node_modules folder inside your NodeBB folder. 
`sudo rm -rf nodebb-plugin-youtube-lite`
`git pull nodebb-plugin-youtube-lite@0.3.2`

Go to Extend > Plugins, activate the plugin then reload your forum.
