### ISSUE TITLE
Resize Error in 0.7.x on playback

### ISSUE THREAD

**Issue by frenchja** [a5mith/nodebb-plugin-youtube-lite#13]
Testing in 0.7.x with Persona 0.1.56.  The poster resizes to 100% width: 
![screen shot 2015-05-28 at 7 42 33 pm](https://cloud.githubusercontent.com/assets/720035/7874204/0cd343c4-0572-11e5-9f9f-35167a524e8d.png)

But the video is left-aligned and bound by the original height instead of the 100% width:

![screen shot 2015-05-28 at 7 42 18 pm](https://cloud.githubusercontent.com/assets/720035/7874211/22e4b9cc-0572-11e5-93b5-70d1224cfd0e.png)

**Comment by thelinuxlich** [comment]
+1 that's happening with me on latest nodebb and persona

**Comment by Hukadan** [comment]
That is not really a plugin problem. You can add the following lines in your custom CSS to solve the issue : 
```css
.topic .posts .content iframe {
    max-width: 100%;
}
```
With persona theme, [it is set at 85% by default](https://github.com/NodeBB/nodebb-theme-persona/blob/master/less/topic.less#L289).

**Comment by a5mith** [comment]
Closing as not a plugin issue.
