### ISSUE TITLE
Links that are not Youtube links are treated as such

### ISSUE THREAD

**Issue by Hukadan** [a5mith/nodebb-plugin-youtube-lite#15]
Hi,

Using the unified regular expression introduced in [this commit](https://github.com/a5mith/nodebb-plugin-youtube-lite/commit/aee6769d4025ad4d87bc4e2121a9dd5dc890ecc5) , some links that were not Youtube links were treated at such leading to broken video links. I had to revert this commit to make the plugin work properly again. Did I miss something or is this regular expression too broad ?

Thank for this plugin anyway.

**Comment by a5mith** [comment]
Can you provide some links that don't work so I can test, regexr seems to believe the regex is fine and I am unable to grab any data from links other than youtube.

**Comment by Hukadan** [comment]
I saw on the Nodebb forum that you managed to reproduce the issue. I can try to find links that did not work if you still need some.

**Comment by a5mith** [comment]
Fixed in https://github.com/a5mith/nodebb-plugin-youtube-lite/commit/26a342937964c271cd2b1b909d397b3681a01980. Update the plugin to latest. :thumbsup:
