### ISSUE TITLE
Funny Layout

### ISSUE THREAD

**Issue by tedr56** [a5mith/nodebb-plugin-youtube-lite#17]
I'm not sure if it's my setup.
But it appears since a nodebb reset

When posting a youtube video, the layout is off.

![phoronix1](https://cloud.githubusercontent.com/assets/186070/9582780/c0ae16e6-5007-11e5-8bcc-ba793ffb9720.png)

It seems to have the correct container size though.

One way to get it right is to edit the post. But on refresh, it's gone again.

**Comment by a5mith** [comment]
Not you as well. Can you throw your contents of lazy-js.js into a pastebin. Plox.

**Comment by NormandoHall** [comment]
The same for me

![image](https://cloud.githubusercontent.com/assets/2943127/9722980/e7244008-558d-11e5-85df-097f03977167.png)

**Comment by NormandoHall** [comment]
Hi @a5mith 

There is no lazy-js.js link in source. Take a look at:

http://vapeandoargentina.com.ar/topic/2360/clt-infinite-v3-mutation-x-v3-revision-y-concurso

**Comment by a5mith** [comment]
Can you all provide me with your current versions of NodeBB. I'm not sure if a change has broken this, or if the plugin itself is at fault. 

It's broken on mine, running latest master, if anyone is running stable 0.8.whatever it is, can you run `git rev-parse HEAD` and provide this as well. 

Mine: ffff8093ba0721

**Comment by NormandoHall** [comment]
Mine: 8ff79af6b916b1741f957968f7cab06b68a406b2

**Comment by a5mith** [comment]
I've located the issue. Just working out why it's not loading the video title, then will release an update.

**Comment by a5mith** [comment]
Sod it, may as well update it to work with Youtube API v3 while I'm here, give me a bit longer.

**Comment by NormandoHall** [comment]
:+1:

**Comment by a5mith** [comment]
This will be updated this evening. But not to youtube v3, that will be a side project in the next major release.

**Comment by a5mith** [comment]
Apologies for the delays, 0.4.7 is now the latest version of this plugin. 

Caveat: The v2 API has been disabled on youtubes end so video titles will just say Loading... I am going to branch this plugin and get V3 working. I already have the code for this, so it shouldn't be too long. But you will all need an api key from Google Developer Tools as it won't work without one, so I need to build the ACP page to get the information into the call.

**Comment by NormandoHall** [comment]
Excelent news @a5mith ! I was update to 0.4.7 and at least shows very good with this little "loading" text.

Thank you so much

Regards
