### ISSUE TITLE
Coub embed not working - using with nodebb 6.0

### ISSUE THREAD

**Issue by Kuznetsof** [a5mith/nodebb-plugin-youtube-lite#6]
Is the plugin suppose to embed coubs?

**Comment by a5mith** [comment]
No, the coubs plugin was a fork of this plugin, unfortunately the developer didn't change any of the package details, so it installs my plugin instead, I did submit a pull request that changes this information, but that PR hasn't been pushed to npm. Create an issue [here](https://github.com/kosyak/nodebb-plugin-coub/issues) asking the developer to push the package.json changes to npm and update to 0.6.x while he's at it. If you get no reply, I'll create a new plugin that will allow the embed of coub videos, as it does seem like a wanted plugin.
